# Generated by Django 6.0.5 on 2026-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('dog', 'Dog Stuff'), ('gym', 'Gym'), ('housework', 'Housework'), ('shopping', 'Shopping'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('notStarted', 'Not Started'), ('inProgress', 'In Progress'), ('completed', 'Completed')], default='notStarted', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=200),
        ),
    ]
